import { Opportunity } from "./types";

// Sample opportunity data for the MVP
export const opportunities: Opportunity[] = [
  {
    id: "1",
    title: "Google Summer of Code 2026",
    category: "Internship",
    deadline: "2026-04-15",
    location: "Remote",
    description: "Contribute to open source projects with mentorship from experienced developers. Earn a stipend while building real-world software.",
    applyLink: "https://summerofcode.withgoogle.com",
    organization: "Google",
    eligibility: "Ages 18+, students or open-source beginners",
    amount: "$1,500 – $6,600",
  },
  {
    id: "2",
    title: "MLH Global Hack Week",
    category: "Hackathon",
    deadline: "2026-06-01",
    location: "Virtual",
    description: "A week-long hackathon with daily challenges, workshops, and prizes. Build projects, learn new tech, and connect with hackers worldwide.",
    applyLink: "https://ghw.mlh.io",
    organization: "Major League Hacking",
    eligibility: "All ages, beginner-friendly",
  },
  {
    id: "3",
    title: "Mastercard Foundation Scholars Program",
    category: "Scholarship",
    deadline: "2026-05-30",
    location: "Africa / Global",
    description: "Full scholarship covering tuition, accommodation, and living expenses at top universities for young Africans with academic talent and leadership potential.",
    applyLink: "https://mastercardfdn.org/scholars",
    organization: "Mastercard Foundation",
    eligibility: "Ages 18–25, African nationals",
    amount: "Full tuition + stipend",
  },
  {
    id: "4",
    title: "Outreachy Internship",
    category: "Fellowship",
    deadline: "2026-03-25",
    location: "Remote",
    description: "Paid remote internships in open source and open science for people subject to systemic bias and underrepresentation in tech.",
    applyLink: "https://www.outreachy.org",
    organization: "Software Freedom Conservancy",
    eligibility: "Ages 18+, underrepresented groups in tech",
    amount: "$7,000",
  },
  {
    id: "5",
    title: "ALX Software Engineering Program",
    category: "Bootcamp",
    deadline: "2026-07-15",
    location: "Remote",
    description: "12-month intensive software engineering program with project-based learning, peer collaboration, and career support.",
    applyLink: "https://www.alxafrica.com",
    organization: "ALX",
    eligibility: "Ages 18+, no prior experience needed",
  },
  {
    id: "6",
    title: "Imagine Cup 2026",
    category: "Competition",
    deadline: "2026-04-30",
    location: "Global",
    description: "Microsoft's annual technology competition for students. Build innovative solutions using Azure and compete for $100,000 in prizes.",
    applyLink: "https://imaginecup.microsoft.com",
    organization: "Microsoft",
    eligibility: "Ages 16+, enrolled students",
    amount: "$100,000 grand prize",
  },
  {
    id: "7",
    title: "Rhodes Scholarship",
    category: "Scholarship",
    deadline: "2026-10-01",
    location: "Oxford, UK",
    description: "The world's oldest international scholarship for postgraduate study at the University of Oxford. Covers all expenses for 2–3 years.",
    applyLink: "https://www.rhodeshouse.ox.ac.uk",
    organization: "Rhodes Trust",
    eligibility: "Ages 19–25, bachelor's degree holders",
    amount: "Full funding",
  },
  {
    id: "8",
    title: "HackMIT 2026",
    category: "Hackathon",
    deadline: "2026-09-10",
    location: "Cambridge, MA, USA",
    description: "MIT's annual hackathon bringing together 1,000+ hackers to build creative projects in 24 hours. Travel reimbursement available.",
    applyLink: "https://hackmit.org",
    organization: "MIT",
    eligibility: "College students worldwide",
  },
  {
    id: "9",
    title: "UN Youth Delegate Programme",
    category: "Fellowship",
    deadline: "2026-05-15",
    location: "New York, USA",
    description: "Represent your country's youth at the United Nations General Assembly. Advocate for youth issues on the global stage.",
    applyLink: "https://www.un.org/youth",
    organization: "United Nations",
    eligibility: "Ages 18–25",
  },
  {
    id: "10",
    title: "Le Wagon Data Science Bootcamp",
    category: "Bootcamp",
    deadline: "2026-08-01",
    location: "Multiple cities / Remote",
    description: "9-week intensive bootcamp covering Python, SQL, machine learning, and deep learning. Career support and demo day included.",
    applyLink: "https://www.lewagon.com",
    organization: "Le Wagon",
    eligibility: "Ages 18+, basic math knowledge",
    amount: "€6,900",
  },
  {
    id: "11",
    title: "Schwarzman Scholars",
    category: "Scholarship",
    deadline: "2026-09-15",
    location: "Beijing, China",
    description: "One-year fully funded master's program at Tsinghua University focused on global affairs, leadership, and China's role in the world.",
    applyLink: "https://www.schwarzmanscholars.org",
    organization: "Schwarzman Scholars",
    eligibility: "Ages 18–28, bachelor's degree",
    amount: "Full funding",
  },
  {
    id: "12",
    title: "NASA L'SPACE Academy",
    category: "Internship",
    deadline: "2026-06-30",
    location: "Remote / USA",
    description: "Free virtual program where students work on real NASA mission proposals and learn project management, systems engineering, and teamwork.",
    applyLink: "https://www.lspace.asu.edu",
    organization: "NASA / ASU",
    eligibility: "US college students, STEM majors",
  },
  {
    id: "13",
    title: "Global Citizen Year Fellowship",
    category: "Fellowship",
    deadline: "2026-04-20",
    location: "Brazil, India, Senegal",
    description: "Bridge year fellowship for high school graduates. Live abroad, work on social impact projects, and develop leadership skills.",
    applyLink: "https://www.globalcitizenyear.org",
    organization: "Global Citizen Year",
    eligibility: "Ages 17–20, high school graduates",
    amount: "Need-based financial aid",
  },
  {
    id: "14",
    title: "DevFest Hackathon",
    category: "Hackathon",
    deadline: "2026-11-01",
    location: "Worldwide",
    description: "Google Developer Groups' flagship community hackathon. Build with Google technologies and win prizes while learning from experts.",
    applyLink: "https://developers.google.com/community/devfest",
    organization: "Google Developer Groups",
    eligibility: "All ages, all skill levels",
  },
  {
    id: "15",
    title: "Codecademy Pro Scholarship",
    category: "Bootcamp",
    deadline: "2026-05-01",
    location: "Remote",
    description: "Free 6-month access to Codecademy Pro for learners from underrepresented backgrounds. Learn web dev, data science, or cybersecurity.",
    applyLink: "https://www.codecademy.com/scholarships",
    organization: "Codecademy",
    eligibility: "Ages 16+, underrepresented in tech",
  },
  // ─── University Scholarships ───────────────────────────────────────
  {
    id: "uni-1",
    title: "DAAD Scholarships for Development-Related Courses",
    category: "University Scholarship",
    deadline: "2026-08-31",
    location: "Germany",
    description: "Fully funded Master's and PhD scholarships at German universities for students from developing countries. Covers tuition, living expenses, and travel.",
    applyLink: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    organization: "DAAD (German Academic Exchange Service)",
    eligibility: "Bachelor's degree holders from developing countries",
    amount: "€934–€1,300/month + tuition",
    level: "Master",
    funding: "Fully funded",
  },
  {
    id: "uni-2",
    title: "Chevening Scholarships",
    category: "University Scholarship",
    deadline: "2026-11-03",
    location: "United Kingdom",
    description: "UK government's global scholarship programme for future leaders to pursue a one-year Master's at any UK university. Fully funded.",
    applyLink: "https://www.chevening.org/scholarships/",
    organization: "UK Foreign, Commonwealth & Development Office",
    eligibility: "2+ years work experience, return to home country",
    amount: "Full tuition + living costs + flights",
    level: "Master",
    funding: "Fully funded",
  },
  {
    id: "uni-3",
    title: "Erasmus Mundus Joint Master Degrees",
    category: "University Scholarship",
    deadline: "2026-10-15",
    location: "Europe (multiple countries)",
    description: "Study in at least two European countries with a fully funded scholarship covering tuition, travel, and a monthly allowance.",
    applyLink: "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters-scholarships",
    organization: "European Commission",
    eligibility: "Bachelor's degree holders worldwide",
    amount: "€1,400/month + tuition + travel",
    level: "Master",
    funding: "Fully funded",
  },
  {
    id: "uni-4",
    title: "Fulbright Foreign Student Program",
    category: "University Scholarship",
    deadline: "2026-06-15",
    location: "United States",
    description: "Prestigious program for graduate students to study at US universities. Covers tuition, living stipend, airfare, and health insurance.",
    applyLink: "https://foreign.fulbrightonline.org/",
    organization: "U.S. Department of State",
    eligibility: "Bachelor's degree holders, non-US citizens",
    amount: "Full funding",
    level: "Master",
    funding: "Fully funded",
  },
  {
    id: "uni-5",
    title: "Commonwealth Scholarships for Developing Countries",
    category: "University Scholarship",
    deadline: "2026-12-18",
    location: "United Kingdom",
    description: "Full scholarships for Master's and PhD study at UK universities for citizens of Commonwealth developing countries.",
    applyLink: "https://cscuk.fcdo.gov.uk/scholarships/",
    organization: "Commonwealth Scholarship Commission",
    eligibility: "Citizens of developing Commonwealth countries",
    amount: "Full tuition + stipend + flights",
    level: "PhD",
    funding: "Fully funded",
  },
  {
    id: "uni-6",
    title: "ETH Zurich Excellence Masters Scholarships",
    category: "University Scholarship",
    deadline: "2026-12-15",
    location: "Switzerland",
    description: "Merit-based scholarships for outstanding Master's students at ETH Zurich, covering tuition and living costs.",
    applyLink: "https://ethz.ch/students/en/studies/financial/scholarships/excellencescholarship.html",
    organization: "ETH Zurich",
    eligibility: "Excellent academic record, any nationality",
    amount: "CHF 12,000/semester + tuition waiver",
    level: "Master",
    funding: "Fully funded",
  },
  {
    id: "uni-7",
    title: "University of Melbourne Graduate Research Scholarships",
    category: "University Scholarship",
    deadline: "2026-10-31",
    location: "Australia",
    description: "Fully funded PhD and Master's by Research scholarships covering tuition, living allowance, and relocation grant.",
    applyLink: "https://scholarships.unimelb.edu.au/awards/graduate-research-scholarships",
    organization: "University of Melbourne",
    eligibility: "International students with strong academic record",
    amount: "AUD $37,000/year + tuition",
    level: "PhD",
    funding: "Fully funded",
  },
  {
    id: "uni-8",
    title: "Turkish Government Scholarships (Türkiye Bursları)",
    category: "University Scholarship",
    deadline: "2026-02-20",
    location: "Turkey",
    description: "Scholarships for Diploma, Bachelor's, Master's, and PhD programs at Turkish universities. Includes language course, tuition, and monthly stipend.",
    applyLink: "https://www.turkiyeburslari.gov.tr/en",
    organization: "Republic of Türkiye",
    eligibility: "International students, all levels",
    amount: "Full tuition + stipend + accommodation",
    level: "Bachelor",
    funding: "Fully funded",
  },
];
